<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="Owner-PC" name="com.application.test.ApplicationTest" tests="7" failures="1" timestamp="16 Feb 2022 01:13:29 GMT" time="221.405" errors="0">
  <testcase name="VerifyApplicationTitle" time="21.027" classname="com.application.test.ApplicationTest"/>
  <testcase name="VerifyApplicationHeader" time="21.260" classname="com.application.test.ApplicationTest"/>
  <testcase name="VerifyApplicationLogin" time="35.250" classname="com.application.test.ApplicationTest">
    <skipped/>
  </testcase> <!-- VerifyApplicationLogin -->
  <testcase name="VerifyApplicationLogout" time="50.688" classname="com.application.test.ApplicationTest"/>
  <testcase name="VerifyApplicationLogin" time="34.530" classname="com.application.test.ApplicationTest">
    <failure type="java.lang.AssertionError" message="Login is not successful">
      <![CDATA[java.lang.AssertionError: Login is not successful
at org.junit.Assert.fail(Assert.java:88)
at com.application.pages.LoginPage.VerifySuccessfulLogin(LoginPage.java:109)
at com.application.test.ApplicationTest.VerifyApplicationLogin(ApplicationTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyApplicationLogin -->
  <testcase name="VerifyApplicationLogin" time="38.414" classname="com.application.test.ApplicationTest"/>
  <testcase name="VerifyForgotPasswordFeature" time="20.236" classname="com.application.test.ApplicationTest"/>
</testsuite> <!-- com.application.test.ApplicationTest -->
